finished mkl-6 Design and Develope login template
Rantama/MAERK pull request #7
Opened 2016-10-27 20:29 UTC by Rantama

-completed login template

2016-10-27 20:35 UTC, tarunktk reviewed
-login page works
-responsive

2016-10-27 21:08 UTC, lchapoy requested changes
Design changes

2016-10-27 21:08 UTC, lchapoy commented on client/app/account/login/login.html
> +                                <button class="md-raised" class="btn btn-inverse btn-lg btn-login" type="submit">
The button does not have material design

2016-10-27 21:08 UTC, lchapoy commented on client/app/account/login/login.html
> +<div layout-margin flex layout="row" layout-align="center">
The login shouldn't  take all the length, just the required length

2016-10-28 14:47 UTC, tarunktk reviewed
side panel removed.
used angular material
responsive

2016-10-28 15:16 UTC, lchapoy approved these changes

2016-10-28 15:16 UTC, merged